
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "G:/STM32CubeCLT_1.22.0/CMake/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:28 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
...
